# Generated by Django 2.2.6 on 2019-12-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.EmailField(max_length=100, verbose_name='email address')),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('inquiry_is_processed', models.BooleanField(default=False, verbose_name='Processed')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='sent on')),
            ],
        ),
    ]
