# Generated by Django 2.2.6 on 2019-12-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='registration_processed',
            field=models.BooleanField(default=False),
        ),
    ]
