# Generated by Django 2.2.6 on 2019-12-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_register_registration_processed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='registration_processed',
        ),
        migrations.AddField(
            model_name='register',
            name='registration_is_processed',
            field=models.BooleanField(default=False, verbose_name='Processed'),
        ),
    ]
